language: python
sudo: required
dist: xenial
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database test_provenance;' -U postgres
env:
  global:
    - DB=postgresql://postgres@localhost/test_provenance

python:
  # We don't actually use the Travis Python, but this keeps it organized. For now only python 3.5 is supported.
  # - "2.7"
  # - "3.3"
  # - "3.4"
  - "3.5"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda.
  - conda info -a
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy
  - conda install -c conda-forge pyarrow
  - pip install -r test_requirements.txt
  - python setup.py install

script: python setup.py test
